image: node:12.13.0-alpine

stages:
  - test
  - deploy

deploy-firestore:
  stage: deploy
  before_script:
    - npm i -g firebase-tools
    - npm i -g @angular/cli
  script:
    - firebase deploy --only firestore --token $FIREBASE_TOKEN
  only:
    refs:
      - master
    changes:
      - firebase-config/firestore.rules
      - firebase-config/firestore.indexes.json

deploy-functions:
  stage: deploy
  before_script:
    - npm i -g firebase-tools
    - npm i -g @angular/cli
  script:
    - cd functions
    - npm install
    - cd ..
    - firebase deploy --only functions --token $FIREBASE_TOKEN
  only:
    refs:
      - master
    changes:
      - functions/**/*

e2e:
  stage: test
  image: cypress/browsers:node12.4.0-chrome76
  script:
    - npm install
    - npm run e2e
  only:
    - master
    - dev
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules

prod-hosting:
  stage: deploy
  before_script:
    - npm i -g firebase-tools
    - npm i -g @angular/cli
  script:
    - npm install
    - npm run-script build
    - firebase deploy --only hosting --token $FIREBASE_TOKEN
  only:
    - master
  environment:
    name: production
    url: https://timetracker-ca7f3.web.app/
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules
